baseURL: "https://haiyi-mei.com"
languageCode: "en-us"
title: "Haiyi Mei"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: true

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
googleAnalytics: G-8T9VFZSLDR

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    -
    # - identifier: blog
    #   name: Blog
    #   title: Blog posts
    #   url: /blogs
    #   weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Haiyi Mei"
  description: My personal website
  # staticPath: ""  # The path to serve the static files from
  favicon: /images/avatar.png

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "dark"

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
    # textColor:
    # secondaryTextColor:
    # backgroundColor:
    # secondaryBackgroundColor:
    # primaryColor:
    # secondaryColor:

    darkmode:
      textColor:
      secondaryTextColor:
      backgroundColor:
      secondaryBackgroundColor:
      primaryColor: "#8abecc"
      secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: " " # Brand name for the brand | default is the title variable
    disableSearch: true
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Haiyi Mei"
    subtitle: "梅海艺"
    content: "Research Fellow at [SenseTime](https://www.sensetime.com) Research, focusing on 3D <u>synthetic data</u> generation for computer vision tasks."
    image: /images/avatar.png
    url: "https://space.bilibili.com/30424533"
    bottomImage:
      enable: false
    # roundImage: true # Make hero image circular | default false
    button:
      enable: false
      name: "Resume"
      url: "/HaiyiMei_Resume.pdf"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/HaiyiMei
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/haiyimei/
        - icon: fa-brands fa-google-scholar
          url: https://scholar.google.com/citations?user=TOZ9wR4AAAAJ
        - icon: fa-solid fa-envelope
          url: mailto:haiyimei@gmail.com

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me-paris.jpg"
    content: |-
      I'm a research fellow working on Computer Graphics and Computer Vision at SenseTime Research.

      I focus on synthetic data generation for computer vision tasks, mainly on 3D human related tasks, such as human mesh recovery, human nerf, etc.
    skills:
      enable: true
      title: "Skills I'm working with:"
      items:
        - "Python"
        - "C++"
        - "Unreal Engine"
        - "Blender"
        - "PyTorch"
        - "Mitsuba"
        - "Git"
        - "Docker"

  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Mid-Level Algorithm Researcher"
        company: "SenseTime"
        companyUrl: "https://www.sensetime.com"
        date: "June 2021 - Present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: false
        content: |-
          I am working on <u>synthetic data</u> generation for computer vision tasks.

          ----

          ##### XRFeitoria

          I spearheaded the development of <a href="https://github.com/openxrlab/xrfeitoria">
          XRFeitoria <img src="https://img.shields.io/github/stars/openxrlab/xrfeitoria" alt="XRFeitoria"/></a>,
          a rendering toolbox designed to streamline synthetic data generation.
          This tool simplifies the construction of pipelines 
          for topics including human mesh recovery, novel view synthesis, etc, 
          leading to the publishing of several papers within a short timeframe:

          - [(ICCV 2023) SynBody: Synthetic Dataset with Layered Human Models for 3D Human Perception and Modeling](https://synbody.github.io/)
          - [(ICCV 2023) Zolly: Zoom Focal Length Correctly for Perspective-Distorted Human Mesh Reconstruction](https://wenjiawang0312.github.io/projects/zolly/)
          - [(ICCV 2023) SHERF: Generalizable Human NeRF from a Single Image](https://skhu101.github.io/SHERF/)
          - [(NIPS 2023) PrimDiffusion: Volumetric Primitives Diffusion for 3D Human Generation](https://frozenburning.github.io/projects/primdiffusion/)
          - [(Preprint) HumanLiff: Layer-wise 3D Human Generation with Diffusion Model](https://skhu101.github.io/HumanLiff/)

          ##### SynBody

          I held a principal role in designing [<i class="fa-regular fa-file-lines"></i> SynBody](https://synbody.github.io/),
          a large-scale synthetic dataset with layered human models.

          - Participated in designing SMPL-XL, which enriches SMPL-X in hair, garments, accessories, and textures.
          - Built a System of synthetic data generation as a Software-as-a-Service (SaaS) platform,
          including layered human creation, motion retargeting, scene composition, rendering pipeline, and flow control.
          - Published a paper presented at ICCV 2023 as co-first author.

          ##### Demo videos
          I'm proficient in crafting advanced technology demonstration videos.
          - [(ICCV 2023) SynBody](https://synbody.github.io/)
          - [(Github) XRFeitoria](https://github.com/openxrlab/xrfeitoria#introduction)
          - [(NIPS 2023) SMPLer-X](https://caizhongang.com/projects/SMPLer-X/)
          - [(Preprint) Digital Life Project](https://digital-life-project.com/)

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: XRFeitoria
        content: |-
          Rendering toolbox for generating synthetic data.
          - Control over engine (UE/Blender) through RPC using system python.
          - Support multiple engine backends, including Unreal Engine and Blender.
          - Render photorealistic images with ground-truth annotations.
          - Manage assets/cameras, including import, place, export, and delete.
          - CLI tools to render images from a mesh file.
          - Streamline building rendering pipelines across various domains, effectively implemented in over **6 projects**.
        image: /images/projects/XRFeitoria_small.gif
        url: https://github.com/openxrlab/xrfeitoria
        featured:
          name: Open-source Toolbox
          link: https://github.com/openxrlab/xrfeitoria
        badges:
          - "Python"
          - "C++"
          - "Blender"
          - "Unreal Engine"
        links:
          - icon: fab fa-github
            url: https://github.com/openxrlab/xrfeitoria
            title: Github
          - icon: fa-solid fa-book
            url: https://xrfeitoria.readthedocs.io
            title: Docs
          - icon: fa-brands fa-python
            url: https://pypi.org/project/xrfeitoria/
            title: PyPI

      - title: SynBody
        content: |-
          A large-scale synthetic dataset with massive number of subjects and high-quality annotations.
          
          It supports various research topics, including human mesh recovery and novel view synthesis for human (Human NeRF).
        image: /images/projects/SynBody_small.gif
        url: https://synbody.github.io/
        featured:
          name: Paper@ICCV2023
          link: https://synbody.github.io/
        badges:
          - "Layered Human"
          - "Dataset"
          - "XRFeitoria"
        links:
          - icon: fa-solid fa-house
            url: https://synbody.github.io/
            title: Homepage
          - icon: fa-solid fa-database
            url: https://openxlab.org.cn/datasets/OpenXDLab/SynBody/
            title: Dataset
      
      - title: Zolly
        content: Zoom Focal Length Correctly for Perspective-Distorted Human Mesh Reconstruction
        image: /images/projects/zolly.jpg
        url: https://wenjiawang0312.github.io/projects/zolly/
        featured:
          name: Paper@ICCV2023
          link: https://wenjiawang0312.github.io/projects/zolly/
        badges:
          - "Human Mesh Reconstruction"
          - "XRFeitoria"
        links:
          - icon: fa-solid fa-house
            url: https://wenjiawang0312.github.io/projects/zolly/
          - icon: fab fa-github
            url: https://github.com/WenjiaWang0312/Zolly
            title: Paper

      - title: SHERF
        content: Learns a Generalizable Human NeRF to animate 3D humans from a single image.
        url: https://skhu101.github.io/SHERF/
        image: /images/projects/SHERF.png
        featured:
          name: Paper@ICCV2023
          link: https://skhu101.github.io/SHERF/
        badges:
          - "Human NeRF"
          - "XRFeitoria"
        links:
          - icon: fa-solid fa-house
            url: https://skhu101.github.io/SHERF/
          - icon: fab fa-github
            url: https://github.com/skhu101/SHERF

      - title: PrimDiffusion
        content: Generates 3D human by denoising a set of volumetric primitives.
        url: https://frozenburning.github.io/projects/primdiffusion/
        image: /images/projects/primdiffusion.gif
        featured:
          name: Paper@NeurIPS2023
          link: https://frozenburning.github.io/projects/primdiffusion/
        badges:
          - "Diffusion"
          - "XRFeitoria"
        links:
          - icon: fa-solid fa-house
            url: https://frozenburning.github.io/projects/primdiffusion/
          - icon: fab fa-github
            url: https://github.com/FrozenBurning/PrimDiffusion

      - title: HumanLiff
        content: Learns the layer-wise 3D human generative model with a unified diffusion process.
        url: https://skhu101.github.io/HumanLiff/
        image: /images/projects/HumanLiff_thumbnail.gif
        featured:
          name: Paper@ArXiv
          link: https://skhu101.github.io/HumanLiff/
        badges:
          - "Diffusion"
          - "XRFeitoria"
        links:
          - icon: fa-solid fa-house
            url: https://skhu101.github.io/HumanLiff/
          - icon: fab fa-github
            url: https://github.com/skhu101/HumanLiff

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Biomedical/Medical Engineering"
        school:
          name: "Shandong University"
          url: "https://en.sdu.edu.cn/"
        date: "2019 - 2022"
        GPA:
        content: |-
          I Published:
          - <i class="fa-regular fa-lightbulb"></i> Patent filed with CNIPA: [CN114429436A](https://patents.google.com/patent/CN114429436A)

      - title: "Visiting Research Intern"
        school:
          name: "Institute of Automation, Chinese Academy of Sciences"
          url: "http://www.nlpr.ia.ac.cn/en/"
        date: "2018 - 2021"
        GPA:
        content: |-
          Starting to work on synthetic data generation for computer vision tasks.

          I Published:
          - <i class="fa-regular fa-lightbulb"></i> Patent filed with CNIPA: [CN113011334A](https://patents.google.com/patent/CN113011334A)
          - <i class="fa-regular fa-file-lines"></i> **Haiyi MEI**, Xiangyu ZHU, Zhen LEI, Rui GAO, Xibo MA. Scene flow prediction with simulated real scenarios. Journal of Graphics, 2022, 43(3): 404-412.

      - title: "Bachelor of Automation"
        school:
          name: "Nanjing University of Science and Technology"
          url: "https://english.njust.edu.cn/"
        date: "2015 - 2019"
        GPA:
        content: |-
          I Published:
          - <i class="fa-regular fa-lightbulb"></i> Patent filed with CNIPA: [CN108453742B](https://patents.google.com/patent/CN108453742B)
          - <i class="fa-regular fa-file-lines"></i> Mian ZHANG, Ying HUANG, **Haiyi MEI**, Yu GUO. Intelligent interaction method for power distribution robot based on Kinect. Journal of Shandong University(Engineering Science), 2018, 48(5): 103-108.
          

          Extracurricular Activities
            - <i class="fa-solid fa-music"></i> Head of the Symphony Orchestra of School, 2016 - 2018
            - <i class="fa-solid fa-music"></i> First Place Award, National University Piano Competition, Chinese Golden Bell Award for Music, 2017

  contact:
    enable: true
    # title: "Custom Name"
    content: |-
      :partying_face: Contact me for any questions or want to collaborate! Always open to new opportunities.
      
      <i class="fa-regular fa-envelope"></i> haiyimei [at] gmail.com
    email: haiyimei@gmail.com
    btnName: Mail me

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false

    copyright: ""
    by: "Haiyi"
    updateDateFormat: "Jan 02, 2006"

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  # customScripts:
